[package]
name = "eagle_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempfile = "3"
structopt = "0.3"
structopt-derive = "0.4"