[package]
name = "demo1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.27.0", features = ["full"]}

[[bin]]
name = "m1"
[[bin]]
name = "my_audio"
