server:
  port: 8113 # 服务端口
  servlet:
    context-path: /kafka
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-abc # 服务名
  kafka:
    producer:
      bootstrap-servers: h131:9092
      acks: all
      retries: 0
      batch-size: 16384

#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


logging:
  level:
    root: debug
