[package]
name = "proc_macro_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0"
quote = "1.0"

[lib]
# https://doc.rust-lang.org/reference/procedural-macros.html
proc-macro = true