server:
  port: 8112 # 服务端口
  servlet:
    context-path: /mysqlPlus
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-mysql-plus # 服务名
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://h131:3306/hsp_mybatis?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: "123456" # 需要配置环境变量MYSQL_PASSWORD
logging:
  level:
    root: info
#  file:
#    name: LOG_PATH/your-log-filename.log # 定义日志文件名和路径
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"