server:
  port: 8112 # 服务端口
  servlet:
    context-path: /eagle
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-mysql # 服务名
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.131:3306/test?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456