[package]
name = "my_err"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.144"
toml = "0.5.9"
failure = "0.1.8"
walkdir = "2.*"
serde_json = "1.0.85"