server:
  port: 8113 #服务端口
  servlet:
    context-path: /mysql
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-mysql # 服务名
  data:
    mongodb:
      uri: mongodb://user:123456@h131:27019/mydb
#      host: 192.168.0.131
#      port: 27019
#      database: im
#      auto-index-creation: true
#      username: root
#      password: 123456
#      authentication-database: admin

#  datasource: # mysql数据库连接
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://h131:3306/hsp_mybatis?useSSL=true&requireSSL=true&verifyServerCertificate=false&characterEncoding=UTF-8
#    username: root
#    password: 123456 # 需要配置环境变量MYSQL_PASSWORD
#  kafka:
#    consumer:
#      bootstrap-servers: h131:9092
#      group-id: "eagle"
#      enable-auto-commit: true
#      auto-commit-interval: 10000
#      auto-offset-reset: latest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


logging:
  level:
    root: debug

#mybatis-plus:
#  typeAliasesPackage: com.eagle.mysql.pojo.entity
#  global-config:
#    db-config:
#      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  mapper-locations: classpath:com/eagle/mysql/mapper/xml/*.xml
#  file:
#    name: LOG_PATH/your-log-filename.log # 定义日志文件名和路径
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
