[package]
name = "e_crossbeam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
crossbeam = "0.8.2"
crossbeam-channel = "0.5.6"
error-chain = "0.12.4"
lazy_static = "1.4.0"
ring = "0.17.0-alpha.11"