version: '3.3'
services:
  mongo:
    restart: always
    # build: .
    image: mongo:5.0.14
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      # 数据目录  挂载出来后，即使删除容器，再用该挂载数据与docker-compose.yml文件启动容器，即可恢复到原来的数据以及用户信息
      - /usr/local/docker/mongodb/db:/data/db
      # 自定义数据备份目录，可以定时全量备份数据出来
      - ./mybackup:/mybackup
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
      # 缓存大小配置为使用 1.5GB ， 考虑服务器中还有其他服务需要占用内存，可自定义大小
      - wiredTigerCacheSizeGB=1.5

    # --auth 开启权限认证       --noauth 关闭权限认证，找回密码时使用此配置重启服务
    command: mongod --auth