use std::sync::Mutex;
use lazy_static::lazy_static;
use serde_json::{json, Value};
lazy_static! {
         pub static ref  stable_value: Value = json!({
  "fn_index": 189,
  "data": [
    "task(skmdwgp8q70s46z)",
    "{{best quality}}, {{masterpiece}}, {{ultra-detailed}}, {illustration}, {detailed light}, {an extremely delicate and beautiful}, a girl, {beautiful detailed eyes}, stars in the eyes, messy floating hair, colored inner hair, Starry sky adorns hair, depth of field, pretty girl, red hair, long legs",
    "lowres, bad anatomy, text, error, extra digit, fewer digits, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, {blurry:1.1}, missing arms",
    [],
    30,
    "Euler a",
    false,
    false,
    1,
    1,
    7,
    -1,
    -1,
    0,
    0,
    0,
    false,
    512,
    512,
    false,
    0.7,
    2,
    "Latent",
    0,
    0,
    0,
    [],
    "None",
    false,
    false,
    "LoRA",
    "None",
    1,
    1,
    "LoRA",
    "None",
    1,
    1,
    "LoRA",
    "None",
    1,
    1,
    "LoRA",
    "None",
    1,
    1,
    "LoRA",
    "None",
    1,
    1,
    "Refresh models",
    false,
    false,
    "positive",
    "comma",
    0,
    false,
    false,
    "",
    "Seed",
    "",
    "Nothing",
    "",
    "Nothing",
    "",
    true,
    false,
    false,
    false,
    0,
    [
      {
        "name": "E:\\BaiduNetdiskDownload\\novelai-webui\\outputs\\txt2img-images\\00000-4100598862-{{best quality}}, pretty girl, blue hair, long legs.png",
        "data": "file=E:\\BaiduNetdiskDownload\\novelai-webui\\outputs\\txt2img-images\\00000-4100598862-{{best quality}}, pretty girl, blue hair, long legs.png",
        "is_file": true
      }
    ],
    "{\"prompt\": \"{{best quality}}, pretty girl, blue hair, long legs\", \"all_prompts\": [\"{{best quality}}, pretty girl, blue hair, long legs\"], \"negative_prompt\": \"lowres, bad anatomy, text, error, extra digit, fewer digits, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, {blurry:1.1}, missing arms\", \"all_negative_prompts\": [\"lowres, bad anatomy, text, error, extra digit, fewer digits, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, {blurry:1.1}, missing arms\"], \"seed\": 4100598862, \"all_seeds\": [4100598862], \"subseed\": 1009306110, \"all_subseeds\": [1009306110], \"subseed_strength\": 0, \"width\": 512, \"height\": 512, \"sampler_name\": \"Euler a\", \"cfg_scale\": 7, \"steps\": 20, \"batch_size\": 1, \"restore_faces\": false, \"face_restoration_model\": null, \"sd_model_hash\": \"89d59c3dde\", \"seed_resize_from_w\": 0, \"seed_resize_from_h\": 0, \"denoising_strength\": null, \"extra_generation_params\": {}, \"index_of_first_image\": 0, \"infotexts\": [\"{{best quality}}, pretty girl, blue hair, long legs\\nNegative prompt: lowres, bad anatomy, text, error, extra digit, fewer digits, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, {blurry:1.1}, missing arms\\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 4100598862, Size: 512x512, Model hash: 89d59c3dde, Model: final-prune, Clip skip: 2, ENSD: 31337\"], \"styles\": [], \"job_timestamp\": \"20230430143519\", \"clip_skip\": 2, \"is_using_inpainting_conditioning\": false}",
    "<p>{{best quality}}, pretty girl, blue hair, long legs<br>\nNegative prompt: lowres, bad anatomy, text, error, extra digit, fewer digits, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, {blurry:1.1}, missing arms<br>\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 4100598862, Size: 512x512, Model hash: 89d59c3dde, Model: final-prune, Clip skip: 2, ENSD: 31337</p>",
    "<p></p><div class='performance'><p class='time'>Time taken: <wbr>1m 53.03s</p></div>"
  ],
  "session_hash": "ipnrfm3nkdh"
});
    }